name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint Markdown
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install markdownlint-cli2
      run: npm install -g markdownlint-cli2
      
    - name: Run markdown linter
      run: markdownlint-cli2 "**/*.md"
      
    - name: Upload lint results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: lint-results
        path: |
          *.log
          
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build MkDocs site
      run: mkdocs build --strict
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: site
        path: site/
        
  validate-links:
    name: Validate Links
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install linkchecker
        
    - name: Build site
      run: mkdocs build
      
    - name: Check for broken links
      run: |
        mkdocs serve &
        sleep 5
        linkchecker http://localhost:8000 --no-warnings --ignore-url=^mailto: || true